apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - repo: oci://ghcr.io/prometheus-community/charts
    name: kube-state-metrics
    version: 7.2.2
    releaseName: kube-state-metrics
    namespace: kube-state-metrics
