apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostFilesystem
metadata:
  name: host-filesystem
spec:
  match:
    kinds:
      - apiGroups:
          - ""
        kinds:
          - Pod
    excludedNamespaces:
      - istio-system
      - kube-system
      - kubescape
      - local-path-storage
      - node-exporter
  parameters:
    allowedHostPaths:
      - readOnly: true
        pathPrefix: /node/deck/
