apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: accurate
  name: accurate-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
          securityContext:
            $patch: delete
          startupProbe:
            httpGet:
              path: /healthz
              port: health
            failureThreshold: 1000
            periodSeconds: 10
          livenessProbe:
            failureThreshold: 1000
            periodSeconds: 10
      securityContext:
        $patch: delete
