apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
  - name: accurate
    repo: https://cybozu-go.github.io/accurate
    releaseName: accurate
    namespace: accurate
    includeCRDs: true
    valuesInline:
      controller:
        replicas: 1
      image:
        repository: accurate
        tag: debug
patchesStrategicMerge:
  - accurate.yaml
