apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - releaseName: cilium
    repo: https://helm.cilium.io
    name: cilium
    namespace: kube-system
    valuesFile: values.yaml
resources:
  - reference-grant.yaml
