apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: cadvisor
  name: cadvisor
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
