kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      audit-policy-file: /etc/audit-policy/audit-policy.yaml
      audit-log-path: /var/log/audit.log
    extraVolumes:
    - name: host
      hostPath: /etc/audit-policy
      mountPath: /etc/audit-policy
      readOnly: true
      pathType: DirectoryOrCreate
    - name: log
      hostPath: /var/log/kube-apiserver
      mountPath: /var/log
      readOnly: false
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /tmp/kind-manifests
    containerPath: /etc/audit-policy
- role: worker
- role: worker
- role: worker
