apiVersion: v1
kind: Secret
metadata:
  name: grafana
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        isDefault: true
---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
spec:
  containers:
    - name: grafana
      image: grafana/grafana:7.4.3
      env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana
              key: username
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana
              key: password
        - name: GF_PATHS_PROVISIONING
          value: /usr/share/grafana/conf/provisioning
      volumeMounts:
        - name: datasources
          mountPath: /usr/share/grafana/conf/provisioning/datasources
          readOnly: true
  volumes:
    - name: datasources
      configMap:
        name: grafana-datasource
        items:
          - key: prometheus.yaml
            path: prometheus.yaml
