apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
data:
  config.yml: |
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: sample
        static_configs:
          - labels:
              job: sample
              __path__: /var/log/sample.log
        pipeline_stages:
          - regex:
              expression: '^(?P<timestamp>[^\s]+)\s(?P<content>.*)$'
          - timestamp:
              format: RFC3339Nano
              source: timestamp
          - output:
              source: content
  generate.sh: |
    cat <<EOF > /var/log/sample.log
    $(date +%Y-%m-%dT%H):00:01.111111111Z sample 1
    $(date +%Y-%m-%dT%H):00:02.222222222Z sample 2
    $(date +%Y-%m-%dT%H):00:03.333333333Z sample 3
    EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  initContainers:
    - name: generate
      image: bash:5.1.4
      command: ["bash", "-c", "source /etc/promtail/generate.sh"]
      volumeMounts:
        - name: config
          mountPath: /etc/promtail
          readOnly: true
        - name: log
          mountPath: /var/log
          readOnly: false
  containers:
    - name: promtail
      image: grafana/promtail:2.2.0
      volumeMounts:
        - name: config
          mountPath: /etc/promtail
          readOnly: true
        - name: log
          mountPath: /var/log
          readOnly: false
  volumes:
    - name: config
      configMap:
        name: promtail
        items:
          - key: config.yml
            path: config.yml
          - key: generate.sh
            path: generate.sh
    - name: log
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: promtail
spec:
  selector:
    app: promtail
  ports:
    - port: 80
