apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail
data:
  config.yml: |
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: audit
        static_configs:
          - targets:
              - localhost
            labels:
              job: audit
              __path__: /var/log/kube-apiserver/*.log
        pipeline_stages:
          - json:
              expressions:
                timestamp: stageTimestamp
          - timestamp:
              format: RFC3339Nano
              source: timestamp
---
apiVersion: v1
kind: Pod
metadata:
  name: promtail
  labels:
    app: promtail
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-control-plane
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
    - name: promtail
      image: grafana/promtail:2.2.0
      volumeMounts:
        - name: config
          mountPath: /etc/promtail
          readOnly: true
        - name: log
          mountPath: /var/log/kube-apiserver
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: promtail
        items:
          - key: config.yml
            path: config.yml
    - name: log
      hostPath:
        path: /var/log/kube-apiserver
