autoscaleEnabled: false
global:
  logging:
    level: default:debug
meshConfig:
  accessLogFile: /dev/stdout
pilot:
  cni:
    enabled: true
  # https://istio.io/latest/docs/reference/commands/pilot-agent/#envvars
  env:
    ENABLE_NATIVE_SIDECARS: true
    PILOT_ENABLE_ALPHA_GATEWAY_API: true
replicaCount: 1
