autoscaleEnabled: false
global:
  logging:
    level: default:debug
# https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig
meshConfig:
  accessLogFile: /dev/stdout
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
pilot:
  cni:
    enabled: true
  # https://istio.io/latest/docs/reference/commands/pilot-agent/#envvars
  env:
    ENABLE_NATIVE_SIDECARS: true
    PILOT_ENABLE_ALPHA_GATEWAY_API: true
replicaCount: 2
