apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kubescape
  name: node-agent
spec:
  template:
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
