# https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - RequestReceived
rules:
  - level: None
    verbs:
      - get
      - watch
      - list
  - level: Metadata
    resources:
      - group: ""
        resources:
          - pods
    verbs:
      - create
