apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  namespace: grafana
  name: grafana
  labels:
    app.kubernetes.io/component: grafana
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  config:
    auth:
      disable_login_form: "false"
    plugins:
      allow_loading_unsigned_plugins: victoriametrics-datasource
    security:
      admin_user: admin
      admin_password: password
