apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  namespace: grafana
  name: grafana
spec:
  config:
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: password
