apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - command:
            - sleep
            - inf
          image: alpine:3.14.2
          name: alpine
