apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - repo: oci://ghcr.io/grafana/helm-charts
    name: grafana-operator
    version: 5.22.2
    releaseName: grafana-operator
    namespace: grafana-operator
    valuesFile: values.yaml
    includeCRDs: true
