configs:
  cm:
    kustomize.buildOptions: --enable-helm
    url: https://argocd-server.argocd
  params:
    server.insecure: "true"
notifications:
  enabled: false
server:
  service:
    type: NodePort
