apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostFilesystem
metadata:
  name: host-filesystem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kubescape
      - local-path-storage
  parameters:
    allowedHostPaths:
      - readOnly: true
        pathPrefix: /node/deck/
