apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sample
  namespace: argocd
spec:
  destination:
    namespace: sample
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/manifests/sample
    repoURL: https://github.com/yokaze/kind-manifests.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
