apiVersion: v1
kind: Pod
metadata:
  name: burstable
spec:
  containers:
    - command:
        - sleep
        - inf
      image: alpine:3.13.5
      name: alpine
      resources:
        limits:
          cpu: 750m
          memory: 192Mi
        requests:
          cpu: 100m
          memory: 64Mi
