apiVersion: v1
kind: Pod
metadata:
  name: cluster-first-with-host-net
spec:
  containers:
    - command:
        - sleep
        - inf
      image: alpine:3.13.5
      name: alpine
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
