apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: cGFzc3dvcmQ=
  GF_SECURITY_ADMIN_USER: YWRtaW4=
kind: Secret
metadata:
  name: grafana
type: Opaque
---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec:
  deployment:
    envFrom:
      - secretRef:
          name: grafana
    skipCreateAdminAccount: true
  service:
    name: grafana
