apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-operated:9090
  name: prometheus
