apiVersion: v1
kind: Pod
metadata:
  labels:
    app: loki
  name: loki
spec:
  containers:
    - image: grafana/loki:2.3.0
      name: loki
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  ports:
    - port: 3100
  selector:
    app: loki
