apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
spec: {}
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
spec:
  datasources:
    - isDefault: true
      name: Prometheus
      type: prometheus
      url: http://prometheus-operated:9090
  name: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec: {}
