apiVersion: v1
data:
  sample.txt: sample
  sample2.txt: sample2
kind: ConfigMap
metadata:
  name: sample
---
apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - command:
        - sleep
        - inf
      image: alpine:3.13.3
      name: alpine
      volumeMounts:
        - mountPath: /etc/sample
          name: sample
          readOnly: true
  volumes:
    - configMap:
        name: sample
      name: sample
