apiVersion: v1
kind: Pod
metadata:
  name: sample
spec:
  containers:
    - command:
        - sleep
        - inf
      env:
        - name: SAMPLE
          value: hello
      image: alpine:3.14.2
      name: alpine
