apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
    - command:
        - pause
      image: ghcr.io/cybozu/ubuntu-debug:22.04
      name: ubuntu
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  volumes:
    - emptyDir: {}
      name: tmp
