apiVersion: v1
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
kind: ConfigMap
metadata:
  name: prometheus
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  containers:
    - image: prom/prometheus:v2.25.0
      name: prometheus
      volumeMounts:
        - mountPath: /etc/prometheus
          name: config
          readOnly: true
  volumes:
    - configMap:
        items:
          - key: prometheus.yml
            path: prometheus.yml
        name: prometheus
      name: config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus
