apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - services
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
---
apiVersion: v1
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      - job_name: loki
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: ["__meta_kubernetes_endpoints_name"]
            regex: loki
            action: keep
kind: ConfigMap
metadata:
  name: prometheus
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  containers:
    - image: prom/prometheus:v2.25.0
      name: prometheus
      volumeMounts:
        - mountPath: /etc/prometheus
          name: config
          readOnly: true
  serviceAccountName: prometheus
  volumes:
    - configMap:
        items:
          - key: prometheus.yml
            path: prometheus.yml
        name: prometheus
      name: config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 9090
  selector:
    app: prometheus
