apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
        - image: nginx:1.21.5
          name: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample
spec:
  clusterIP: None
  ports:
    - port: 80
  selector:
    app: sample
