apiVersion: v1
kind: Pod
metadata:
  labels:
    app: sample
  name: sample
spec:
  containers:
    - image: nginx:1.21.5
      name: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sample.example.com
  name: sample
spec:
  ports:
    - port: 80
  selector:
    app: sample
