apiVersion: v1
data:
  nginx-port.sh: |
    sed -i "s/80/$0/g" /etc/nginx/conf.d/default.conf
    echo "port $0" > /usr/share/nginx/html/index.html
    nginx -g 'daemon off;'
kind: ConfigMap
metadata:
  name: nginx-port
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-mix
spec:
  ports:
    - port: 8080
      targetPort: web
  selector:
    app: nginx-mix
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-mix
  name: nginx-80
spec:
  containers:
    - command:
        - bash
        - -c
        - source /etc/nginx-port/nginx-port.sh
        - "80"
      image: nginx:1.21.5
      name: nginx
      ports:
        - containerPort: 80
          name: web
      volumeMounts:
        - mountPath: /etc/nginx-port
          name: nginx-port
  volumes:
    - configMap:
        name: nginx-port
      name: nginx-port
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-mix
  name: nginx-1080
spec:
  containers:
    - command:
        - bash
        - -c
        - source /etc/nginx-port/nginx-port.sh
        - "1080"
      image: nginx:1.21.5
      name: nginx
      ports:
        - containerPort: 1080
          name: web
      volumeMounts:
        - mountPath: /etc/nginx-port
          name: nginx-port
  volumes:
    - configMap:
        name: nginx-port
      name: nginx-port
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-mix
  name: nginx-2080
spec:
  containers:
    - command:
        - bash
        - -c
        - source /etc/nginx-port/nginx-port.sh
        - "2080"
      image: nginx:1.21.5
      name: nginx
      ports:
        - containerPort: 2080
          name: web
      volumeMounts:
        - mountPath: /etc/nginx-port
          name: nginx-port
  volumes:
    - configMap:
        name: nginx-port
      name: nginx-port
