apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: vm-operator
    repo: http://victoriametrics.github.io/helm-charts
    name: victoria-metrics-operator
    namespace: vm-operator
    valuesFile: values.yaml
resources:
  - reference-grant.yaml
  - vm-agent.yaml
  - vm-cluster.yaml
