clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: audit
    static_configs:
      - targets:
          - localhost
        labels:
          job: audit
          __path__: /var/log/kube-apiserver/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: stageTimestamp
      - timestamp:
          format: RFC3339Nano
          source: timestamp
