apiVersion: apps/v1
kind: Deployment
metadata:
  name: neco-admission
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: neco-admission
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neco-admission
    spec:
      containers:
      - name: neco-admission
        image: quay.io/cybozu/neco-admission:0.16.1
        args:
          - --cert-dir=/certs
        volumeMounts:
          - name: certs
            mountPath: /certs
          - name: config
            mountPath: /etc/neco-admission
        ports:
          - name: health
            containerPort: 8081
          - name: webhook
            containerPort: 9443
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
            scheme: HTTP
      volumes:
        - name: certs
          secret:
            secretName: neco-admission-webhook
        - name: config
          configMap:
            name: neco-admission-config
