apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neco-admission
resources:
- upstream/manifests.yaml
- certificate.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
configMapGenerator:
- name: neco-admission-config
  files:
  - config.yaml
patchesStrategicMerge:
- webhook.yaml
