$patch: delete
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: neco-admission/neco-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: neco-admission/neco-admission
webhooks:
- name: vdelete.kb.io
  clientConfig:
    service:
      namespace: neco-admission
      name: neco-admission
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - namespaces
- $patch: delete
  name: vapplication.kb.io
- $patch: delete
  name: vgrafanadashboard.kb.io
- $patch: delete
  name: vhttpproxy.kb.io
- $patch: delete
  name: vnetworkpolicy.kb.io
- $patch: delete
  name: vpod.kb.io
- $patch: delete
  name: vpreventdelete.kb.io
