kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: conf.d
        containerPath: /etc/containerd/conf.d
  - role: worker
    extraMounts:
      - hostPath: conf.d
        containerPath: /etc/containerd/conf.d
  - role: worker
    extraMounts:
      - hostPath: conf.d
        containerPath: /etc/containerd/conf.d
  - role: worker
    extraMounts:
      - hostPath: conf.d
        containerPath: /etc/containerd/conf.d
networking:
  disableDefaultCNI: true
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/conf.d"
