kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: node
        containerPath: /node
    extraPortMappings:
      - containerPort: 30080 # Argo CD
        hostPort: 30080
      - containerPort: 30443 # Argo CD
        hostPort: 30443
      - containerPort: 32000 # Traefik
        hostPort: 32000
      - containerPort: 32443 # Traefik
        hostPort: 32443
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            admission-control-config-file: /node/admission/config.yaml
            audit-policy-file: /etc/kubernetes/audit-policy.yaml
            audit-log-path: /var/log/kubernetes/audit/audit.log
          extraVolumes:
            - name: admission
              hostPath: /node/admission
              mountPath: /node/admission
              readOnly: true
              pathType: DirectoryOrCreate
            - name: audit
              hostPath: /node/kubernetes/audit-policy.yaml
              mountPath: /etc/kubernetes/audit-policy.yaml
              readOnly: true
            - name: audit-log
              hostPath: /var/log/kubernetes/audit/
              mountPath: /var/log/kubernetes/audit/
              readOnly: false
  - role: worker
    extraMounts:
      - hostPath: node
        containerPath: /node
  - role: worker
    extraMounts:
      - hostPath: node
        containerPath: /node
  - role: worker
    extraMounts:
      - hostPath: node
        containerPath: /node
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/node/containerd/conf.d"
