kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: node
        containerPath: /node
    extraPortMappings:
      - containerPort: 30080 # Argo CD
        hostPort: 30080
      - containerPort: 30443 # Argo CD
        hostPort: 30443
  - role: worker
    extraMounts:
      - hostPath: node
        containerPath: /node
  - role: worker
    extraMounts:
      - hostPath: node
        containerPath: /node
  - role: worker
    extraMounts:
      - hostPath: node
        containerPath: /node
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/node/containerd/conf.d"
