kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: cluster/conf.d
        containerPath: /etc/containerd/conf.d
      - hostPath: bin
        containerPath: /opt/deck
  - role: worker
    extraMounts:
      - hostPath: cluster/conf.d
        containerPath: /etc/containerd/conf.d
      - hostPath: bin
        containerPath: /opt/deck
  - role: worker
    extraMounts:
      - hostPath: cluster/conf.d
        containerPath: /etc/containerd/conf.d
      - hostPath: bin
        containerPath: /opt/deck
  - role: worker
    extraMounts:
      - hostPath: cluster/conf.d
        containerPath: /etc/containerd/conf.d
      - hostPath: bin
        containerPath: /opt/deck
networking:
  disableDefaultCNI: true
containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/conf.d"
