apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  namespace: grafana
  name: loki
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/component: grafana
  datasource:
    name: Loki
    type: loki
    url: http://loki.loki.svc.cluster.local:3100
    access: proxy
