apiVersion: v1
kind: ConfigMap
metadata:
  namespace: deck
  name: alias
data:
  .bash_aliases: |
    export CURL_CA_BUNDLE=/etc/ssl/certs/cluster-ca/ca.crt
    export HUBBLE_SERVER=hubble-relay.kube-system.svc:80
    PATH=/opt/deck:${PATH}
    . /usr/share/bash-completion/bash_completion
    . <(argocd completion bash)
    . <(cilium completion bash)
    . <(cmctl completion bash)
    . <(gwctl completion bash)
    . <(hubble completion bash)
    . <(istioctl completion bash)
    . <(kubectl completion bash)
    . <(yq completion bash)
