apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: deck
configMapGenerator:
  - name: init-dependency-track
    files:
      - init-dependency-track/feature-dependency-track
      - init-dependency-track/generate-password
      - init-dependency-track/init-all
      - init-dependency-track/set-password
      - init-dependency-track/try-login
resources:
  - alias.yaml
  - init-dependency-track.yaml
  - pilot.yaml
  - service-account.yaml
