apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: deck
  name: pilot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: deck
  name: pilot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: deck
    name: pilot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: ubuntu
  namespace: deck
  name: pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pilot
  template:
    metadata:
      labels:
        app: pilot
    spec:
      containers:
        - command:
            - pause
          image: ghcr.io/cybozu/ubuntu-debug:24.04
          name: ubuntu
          volumeMounts:
            - name: alias
              mountPath: /root/.bash_aliases
              subPath: .bash_aliases
            - name: cluster-ca
              mountPath: /etc/ssl/certs/cluster-ca
              readOnly: true
            - name: tools
              mountPath: /opt/deck
              readOnly: true
            - name: tmp
              mountPath: /tmp
      serviceAccountName: pilot
      volumes:
        - name: alias
          configMap:
            name: alias
        - name: cluster-ca
          configMap:
            name: cluster-ca
        - name: tools
          hostPath:
            path: /node/deck/
        - name: tmp
          emptyDir: {}
