# https://grafana.com/docs/alloy/latest/collect/logs-in-kubernetes/
alloy:
  configMap:
    content: |
      discovery.kubernetes "pod" {
        role = "pod"
      }
      discovery.relabel "pod" {
        targets = discovery.kubernetes.pod.targets
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "job"
          separator = "/"
          replacement = "$1"
        }
        rule {
          source_labels = ["__meta_kubernetes_namespace"]
          action = "replace"
          target_label = "namespace"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_name"]
          action = "replace"
          target_label = "pod"
        }
        rule {
          source_labels = ["__meta_kubernetes_pod_container_name"]
          action = "replace"
          target_label = "container"
        }
        rule {
          source_labels = [
            "__meta_kubernetes_namespace", 
            "__meta_kubernetes_pod_name",
            "__meta_kubernetes_pod_uid",
            "__meta_kubernetes_pod_container_name",
          ]
          action = "replace"
          target_label = "__path__"
          separator = "/"
          replacement = "/var/log/pods/$1_$2_$3/$4/*.log"
        }
      }
      loki.source.kubernetes "pod" {
        targets = discovery.relabel.pod.output
        forward_to = [loki.process.pod.receiver]
      }
      loki.process "pod" {
        forward_to = [loki.write.default.receiver]
      }
      loki.write "default" {
        endpoint {
          url = "http://loki.loki.svc:3100/loki/api/v1/push"
        }
      }
controller:
  type: deployment
