apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: headlamp
helmCharts:
  - releaseName: headlamp
    repo: https://headlamp-k8s.github.io/headlamp
    name: headlamp
    valuesFile: values.yaml
