apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
helmCharts:
  - releaseName: collect-audit
    repo: https://grafana.github.io/helm-charts
    name: alloy
    namespace: logging
    valuesFile: values.yaml
