#!/bin/sh
set -eu
PATH=/opt/deck:/opt/scripts/:${PATH}
SECRET_NAME=dependency-track

if kubectl get secret -n deck ${SECRET_NAME}; then
    exit
fi

PASSWORD=$(openssl rand -hex 8)
kubectl create secret generic -n deck ${SECRET_NAME} \
    --from-literal=username=admin \
    --from-literal=password=${PASSWORD}
