#!/bin/sh
set -eu
PATH=/opt/deck:/opt/scripts:${PATH}

if ! feature-dependency-track; then
    echo 'Dependency-Track is disabled'
    exit
fi

generate-password

# Wait service startup
while curl -sS -o /dev/null http://dependency-track-api-server.dependency-track.svc:8080; do
    sleep 10
done

set-password
test-password

export JWT=$(login-jwt)
add-team
