#!/bin/sh
set -eu
PATH=/opt/deck:${PATH}

if [ $# -eq 2 ]; then
    USERNAME=$1
    PASSWORD=$2
else
    USERNAME=$(kubectl get secret -n deck dependency-track -ojson | jq -r .data.username | base64 -d)
    PASSWORD=$(kubectl get secret -n deck dependency-track -ojson | jq -r .data.password | base64 -d)
fi

RESULT=$(
    curl -sS \
        -X POST http://dependency-track-api-server.dependency-track.svc:8080/api/v1/user/login \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "username=${USERNAME}" \
        --data-urlencode "password=${PASSWORD}" || true
)

if [ "${RESULT}" = "FORCE_PASSWORD_CHANGE" ]; then
    echo "${RESULT}"
    exit
fi

RESULT=$(
    curl -sS -w '\n%{http_code}' \
    -X POST http://dependency-track-api-server.dependency-track.svc:8080/api/v1/user/login \
    -H 'Content-Type: application/x-www-form-urlencoded' \
    --data-urlencode "username=${USERNAME}" \
    --data-urlencode "password=${PASSWORD}"
)

JWT=$(printf '%s' "${RESULT}" | sed '$d')
HTTP_STATUS=$(printf '%s' "${RESULT}" | tail -n1)

if ! [ "${HTTP_STATUS}" = "200" ]; then
    echo "HTTP_STATUS: ${HTTP_STATUS}" > /dev/stderr
    exit 1
fi

echo "${JWT}"
