#!/bin/sh
set -eu
PATH=/opt/deck:/opt/scripts:${PATH}
PASSWORD=$(kubectl get secret -n deck dependency-track -ojson | jq -r .data.password | base64 -d)

while ! login-jwt > /dev/null; do
    # https://docs.dependencytrack.org/getting-started/initial-startup/
    if ! login-jwt admin admin > /dev/null; then
        sleep 5
        continue
    fi

    echo 'Updating password...'
    curl -sS -o /dev/null -X POST 'http://dependency-track-api-server.dependency-track.svc:8080/api/v1/user/forceChangePassword' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode 'username=admin' \
        --data-urlencode 'password=admin' \
        --data-urlencode "newPassword=${PASSWORD}" \
        --data-urlencode "confirmPassword=${PASSWORD}"
done
