#!/bin/sh
set -eu
PATH=/opt/deck:/opt/scripts:${PATH}

USERNAME=$(kubectl get secret -n deck dependency-track -ojson | jq -r .data.username | base64 -d)
PASSWORD=$(kubectl get secret -n deck dependency-track -ojson | jq -r .data.password | base64 -d)

while ! try-login ${USERNAME} ${PASSWORD}; do
    # https://docs.dependencytrack.org/getting-started/initial-startup/
    if ! try-login admin admin; then
        sleep 5
        continue
    fi

    echo "Updating password..."
    curl -sS -o /dev/null -X POST 'http://dependency-track-api-server.dependency-track.svc:8080/api/v1/user/forceChangePassword' \
        -H 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode 'username=admin' \
        --data-urlencode 'password=admin' \
        --data-urlencode "newPassword=${PASSWORD}" \
        --data-urlencode "confirmPassword=${PASSWORD}"
done

if ! try-login ${USERNAME} ${PASSWORD}; then
    echo "Failed to update password"
    exit
fi
