#!/bin/sh
set -eu
PATH=/opt/deck:/opt/scripts:${PATH}
SYFT_FILE=/tmp/sbom.syft.json
CDX_FILE=/tmp/sbom.cdx.json
BASE_URL=http://dependency-track-api-server.dependency-track.svc:8080
API_KEY=$(kubectl get secret -n deck dependency-track-sbom-uploader -ojson | jq -r .data.key | base64 -d)

while true; do
    sleep 60
    for i in $(kubectl get sbomsyfts -n kubescape -oname | cut -d/ -f2); do
        RESOURCE=$(kubectl get sbomsyfts -n kubescape $i -ojson | jq -c)
        printf '%s' "${RESOURCE}" | jq .spec.syft > ${SYFT_FILE}
        syft -q convert ${SYFT_FILE} "-o=cyclonedx-json=${CDX_FILE}"

        PACKAGE_NAME=$(printf '%s' "${RESOURCE}" | jq -r '.metadata.annotations["kubescape.io/image-tag"]' | cut -d: -f1)
        PACKAGE_TAG=$(printf '%s' "${RESOURCE}" | jq -r '.metadata.annotations["kubescape.io/image-tag"]' | cut -d: -f2)

        curl -fsS \
            -X POST "${BASE_URL}/api/v1/bom" \
            -H "X-Api-Key: ${API_KEY}" \
            -F "autoCreate=true" \
            -F "projectName=${PACKAGE_NAME}" \
            -F "projectVersion=${PACKAGE_TAG}" \
            -F "bom=@${CDX_FILE};type=application/json"
    done
done
