apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  namespace: grafana
  name: pyroscope
spec:
  instanceSelector:
    matchLabels:
      app.kubernetes.io/component: grafana
  datasource:
    name: Pyroscope
    type: grafana-pyroscope-datasource
    url: http://pyroscope.pyroscope.svc:4040
    access: proxy
    isDefault: false
    jsonData:
      minStep: '15s'
