apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: kubescape
    repo: https://kubescape.github.io/helm-charts
    name: kubescape-operator
    valuesFile: values.yaml
patches:
  - path: daemonset.yaml
