scrape_configs:
  - job_name: apiserver
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
