apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  namespace: argocd
  name: envoy
spec:
  selector: {}
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
