apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  namespace: kube-state-metrics
  name: kube-state-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  podMetricsEndpoints:
    - port: http
      path: /metrics
    - portNumber: 15020
      path: /stats/prometheus
      relabelConfigs:
        - sourceLabels:
            - __meta_kubernetes_pod_container_name
          regex: istio-proxy
          action: keep
