apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  namespace: victoria-metrics
  name: sidecar
spec:
  selector: {}
  podMetricsEndpoints:
    - portNumber: 15020
      path: /stats/prometheus
      relabelConfigs:
        - sourceLabels:
            - __meta_kubernetes_pod_container_name
          regex: istio-proxy
          action: keep
