apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  namespace: vm-operator
  name: vm-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
  podMetricsEndpoints:
    - port: http
      path: /metrics
    - portNumber: 15020
      path: /stats/prometheus
      relabelConfigs:
        - sourceLabels:
            - __meta_kubernetes_pod_container_name
          regex: istio-proxy
          action: keep
