apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: node-exporter
    repo: https://prometheus-community.github.io/helm-charts
    name: prometheus-node-exporter
    namespace: node-exporter
    valuesFile: values.yaml
