apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: cert-manager
spec:
  commonName: cluster-ca
  duration: 87600h
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: cluster-selfsign
  secretName: cluster-ca
  usages:
    - digital signature
    - key encipherment
    - cert sign
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-ca
spec:
  ca:
    secretName: cluster-ca
