apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argocd
spec:
  hostnames:
    - argocd.localhost
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
  rules:
    - backendRefs:
        - namespace: argocd
          name: argocd-server
          port: 80
