apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kiali
spec:
  hostnames:
    - kiali.localhost
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
  rules:
    - backendRefs:
        - namespace: istio-system
          name: kiali
          port: 20001
