apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vmagent
spec:
  hostnames:
    - vmagent.localhost
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
  rules:
    - backendRefs:
        - namespace: victoria-metrics
          name: vmagent-vm-agent
          port: 8429
