apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: spire
    repo: https://spiffe.github.io/helm-charts-hardened
    name: spire
    skipTests: true
    valuesFile: values.yaml
