apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10000"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: scrape
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/scrape
    repoURL: git://mirror-git:9418/kind-manifests.git
    targetRevision: main
