apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - releaseName: tetragon
    repo: https://helm.cilium.io
    name: tetragon
    namespace: kube-system
    valuesFile: values.yaml
