apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dependency-track
helmCharts:
  - releaseName: dependency-track
    repo: https://dependencytrack.github.io/helm-charts
    name: dependency-track
    namespace: dependency-track
    valuesFile: values.yaml
    version: 0.45.0
resources:
  - reference-grant.yaml
