apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    app.kubernetes.io/component: grafana
spec:
  config:
    auth:
      disable_login_form: "false"
    plugins:
      allow_loading_unsigned_plugins: victoriametrics-datasource
    security:
      admin_user: admin
      admin_password: password
