apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
- releaseName: cert-manager
  repo: https://charts.jetstack.io
  name: cert-manager
  namespace: cert-manager
  valuesFile: values.yaml
