apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
spec:
  hostnames:
    - headlamp.localhost
  parentRefs:
    - kind: Gateway
      name: traefik-gateway
  rules:
    - backendRefs:
        - namespace: headlamp
          name: headlamp
          port: 80
