apiVersion: v1
kind: Namespace
metadata:
  name: spire-sample
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample
  namespace: spire-sample
---
apiVersion: v1
data:
  spiffe-helper.conf: |
    agent_address = "/spiffe-workload-api/spire-agent.sock"
    cert_dir = "/certs"
    svid_file_name = "tls.crt"
    svid_key_file_name = "tls.key"
    svid_bundle_file_name = "ca.pem"
    jwt_svids = [{jwt_audience="test", jwt_svid_file_name="jwt_svid.token"}]
kind: ConfigMap
metadata:
  name: sample
  namespace: spire-sample
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: ubuntu
  name: sample
  namespace: spire-sample
spec:
  containers:
    - command:
        - pause
      image: ghcr.io/cybozu/ubuntu-debug:22.04
      name: ubuntu
      volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /certs
          name: certs
    - args:
        - -config
        - /etc/spiffe-helper.conf
      image: ghcr.io/spiffe/spiffe-helper:0.8.0
      name: spiffe-helper
      volumeMounts:
        - mountPath: /spiffe-workload-api
          name: spiffe-workload-api
          readOnly: true
        - mountPath: /etc/spiffe-helper.conf
          name: config
          readOnly: true
          subPath: spiffe-helper.conf
        - mountPath: /certs
          name: certs
  serviceAccountName: sample
  volumes:
    - emptyDir: {}
      name: tmp
    - csi:
        driver: csi.spiffe.io
        readOnly: true
      name: spiffe-workload-api
    - configMap:
        name: sample
      name: config
    - emptyDir: {}
      name: certs
