apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: squid-mitm
spec:
  commonName: squid.proxy.svc.cluster.local
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cluster-ca
  secretName: squid-mitm
  usages:
    - digital signature
    - key encipherment
    - cert sign
