apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proxy
configMapGenerator:
  - name: squid
    files:
      - squid.conf
  - name: squid-opaque
    files:
      - squid.conf=squid-opaque.conf
resources:
  - certificate.yaml
  - service-entry.yaml
  - squid.yaml
  - squid-opaque.yaml
