apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
        - image: ubuntu/squid:latest
          name: squid
          volumeMounts:
            - name: config
              mountPath: /etc/squid
              readOnly: true
            - name: cache
              mountPath: /var/spool/squid
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: squid
        - name: cache
          hostPath:
            path: /node/squid/
---
apiVersion: v1
kind: Service
metadata:
  name: squid
spec:
  selector:
    app: squid
  ports:
    - appProtocol: TCP
      port: 3128
