apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: argocd
  name: proxy
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git://mirror-git:9418/kind-manifests.git
  proxy: http://squid.proxy.svc:3128
  noProxy: mirror-git
