configs:
  cm:
    kustomize.buildOptions: --enable-helm
    url: https://argocd-server.argocd
  params:
    server.insecure: "true"
notifications:
  enabled: false
# repoServer:
#   env:
#     - name: HTTP_PROXY
#       value: http://squid.proxy.svc:3128
#     - name: HTTPS_PROXY
#       value: http://squid.proxy.svc:3128
#     - name: NO_PROXY
#       value: mirror-git
server:
  service:
    nodePortHttp: 30080
    nodePortHttps: 30443
    type: NodePort
