configs:
  cm:
    kustomize.buildOptions: --enable-helm
    url: https://argocd-server.argocd
  params:
    server.insecure: "true"
notifications:
  enabled: false
repoServer:
  volumeMounts:
    - name: cluster-ca
      mountPath: /etc/ssl/certs
      readOnly: true
  volumes:
    - name: cluster-ca
      configMap:
        name: cluster-ca
server:
  service:
    nodePortHttp: 30080
    nodePortHttps: 30443
    type: NodePort
