apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: samples.yokaze.github.io
spec:
  group: yokaze.github.io
  names:
    kind: Sample
    plural: samples
    singular: sample
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                message:
                  type: string
                priority:
                  type: integer
              type: object
          type: object
      served: true
      storage: true
